SELECT * FROM
(
    SELECT DISTINCT
        IDENTIFICADOR_EMPRESA IDEMPRESA,
        TRIM(NOMBRE_DE_LA_EMPRESA) NOMBRE
    FROM RENASER.BODEGA_EMPRESAS_ORFEO
    WHERE
        ENERGIA = 1
        AND EST_NOMBRE IN ('OPERATIVA', 'EN PROCESO DE LIQUIDACION', 'INTERVENIDA')
        AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
) EMPRESAS,
(
    SELECT 
        ID_MERCADO,
        ARE_ESP_SECUE,
        NOM_MERCADO,
        ESTADO 
    FROM 
        CARG_COMERCIAL_E.MERCADO_EMPRESA 
    WHERE 
        ID_MERCADO = :MERCADO_ARG OR 0 = :MERCADO_ARG 
        AND ESTADO = 'A'
        AND NOM_MERCADO NOT LIKE '%Mercado Prueba%' 
        AND NOM_MERCADO NOT LIKE '%Mercado de Prueba%'
)
WHERE IDEMPRESA = ARE_ESP_SECUE;